# Generated by Django 2.1.4 on 2019-01-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inven_app', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
