# Generated by Django 2.1.4 on 2019-01-11 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inven_app', '0005_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_num', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=25, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inven_app.Location')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inven_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('account', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('product_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('munis_GL_number', models.PositiveIntegerField(blank=True, null=True)),
                ('munis_PO_number', models.PositiveIntegerField(blank=True, null=True)),
                ('munis_PO_date', models.DateField(blank=True, null=True)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inven_app.Approver')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inven_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.CharField(max_length=200)),
                ('VendorWebsite', models.CharField(max_length=200)),
                ('VendorPhone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='order_status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='inven_app.Status'),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inven_app.Vendor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inven_app.Request'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inven_app.Request'),
        ),
    ]
