# Generated by Django 2.1.4 on 2019-01-11 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inven_app', '0006_auto_20190111_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
