# Generated by Django 2.1.4 on 2019-01-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inven_app', '0008_auto_20190111_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inven_app.Approver'),
        ),
    ]
