# Generated by Django 2.1.4 on 2019-03-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inven_app', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
